fix race condition in err goroutines; fix send on wrong goroutine
smallpdf/svg pull request #1
Opened 2017-11-11 06:06 UTC by pdbogen

Howdy!

One bug is pretty serious, which is that on line 172 of svg.go you attempt a send on the wrong error channel; the send should occur on `s.errors` instead of `g.errors`.

Someone less important but still worth fixing, in my opinion, is that the treatment of goroutines and channels with regard to errors has a race condition. Because the order of execution of goroutines is undefined without synchronizing events, it's possible for the `defer close(g.errors)` / `defer close(s.errors)` to actually execute before (or concurrently) with the sub-goroutine send on that channel; this results in a panic, because a send on a closed channel is a fatal error.

I fix this in the PR below with `sync.WaitGroup`, by ensuring that any sending goroutines have exited before closing the corresponding channel.

Thanks,
- Patrick

2017-11-13 08:19 UTC, Shugyousha requested changes
If you can change the t.Logf and the testing I will merge your patches after having tested them more thoroughly. Thanks for the patches!

2017-11-13 08:19 UTC, Shugyousha commented on path.go
> +	var err error
Nitpick: I would prefer to have these two variable declarations before the function call.

2017-11-13 08:19 UTC, Shugyousha commented on path_test.go
> +		dis, _ := svg.ParseDrawingInstructions()
We should check the errors here. The tests will fail without checking (because the output will most likely be wrong) but in order to see what actually went wrong, iterating through the error channel with a require.NoError() is better.

2017-11-13 08:19 UTC, Shugyousha commented on path_test.go
> +			log.Printf("di: %+v, di.M: %+v", di, di.M)
Let's keep the tests as quiet as possible and use t.Logf here instead of log.Printf.

2017-11-13 08:19 UTC, Shugyousha commented on path_test.go
> +			log.Printf("di: %+v, di.M: %+v", di, di.M)
The tests can be simplified by just itereating over the DrawingInstructions like this:

```
+       for _, test := range tests {
+               svg, err := ParseSvg(test.Svg, "test", 0)
+               require.NoError(t, err)
+
+               dis, _ := svg.ParseDrawingInstructions()
+               strux := []*DrawingInstruction{}
+               for di := range dis {
+                       strux = append(strux, di)
+                       log.Printf("di: %+v, di.M: %+v", di, di.M)
+               }
+
+               if len(strux) != len(test.Kinds) {
+                       t.Fatalf("expected %d instructions for test %s, but received %d", len(test.Kinds), test.Description, len(strux))
+               }
+
+               for i, stru := range strux {
+                       if stru.Kind != test.Kinds[i] {
+                               t.Fatalf("expected instruction %d for test %s to be %d, but was %d", i, test.Description, test.Kinds[i], stru.Kind)
+                       }
+
+                       if stru.M == nil {
+                               continue
+                       }
+
+                       if stru.M[0] != test.XCoords[i] {
+                               t.Fatalf("expected X coordinate %d for test %s to be %f, but was %f", i, test.Description, test.XCoords[i], stru.M[0])
+                       }
+
+                       if stru.M[1] != test.YCoords[i] {
+                               t.Fatalf("expected Y coordinate %d for test %s to be %f, but was %f", i, test.Description, test.YCoords[i], stru.M[1])
+                       }
+               }
+       }
```

2017-11-13 08:21 UTC, Shugyousha commented
Ah, you should run `go fmt` over your code as the final step.

2018-01-05 00:28 UTC, pdbogen commented
Thanks for taking a look, @Shugyousha. I've made the requested changes; please let me know if you find anything else that could use some TLC.

2018-01-08 08:21 UTC, Shugyousha commented
Looks good! I have merged your commits into our dev branch. We will test them there and if we don't don't find any issues we will merge them into master. I will close this PR as soon as we have merged your patches into our master branch.

Thanks again!

2018-01-08 08:21 UTC, Shugyousha approved these changes

2018-01-11 16:23 UTC, merged

2018-01-11 16:25 UTC, Shugyousha commented
Your commits are now in master, thanks!